Added check for sending ARP requests with 802.1Q tag and LLC/SNAP framing. Updated NEWS.
git-svn-id: svn+ssh://svn.nta-monitor.com/trunk/opensource/arp-scan@18137 062a1500-4a13-0410-a63b-ee65f32af78f

diff --git a/check-packet b/check-packet
--- a/check-packet
+++ b/check-packet
@@ -36,6 +36,7 @@ SAMPLE02="$srcdir/pkt-custom-request.dat"
 SAMPLE03="$srcdir/pkt-custom-request-padding.dat"
 SAMPLE04="$srcdir/pkt-custom-request-llc.dat"
 SAMPLE05="$srcdir/pkt-custom-request-vlan.dat"
+SAMPLE06="$srcdir/pkt-custom-request-vlan-llc.dat"
 
 echo "Checking simple ARP request packet against $SAMPLE01 ..."
 ARPARGS="--retry=1 --file=- --srcaddr=00:01:02:03:04:05 --arpsha=00:01:02:03:04:05 --arpspa=127.0.0.1"
@@ -114,6 +115,23 @@ if test $? -ne 0; then
    exit 1
 fi
 cmp -s $TMPFILE $SAMPLE05
+if test $? -ne 0; then
+   rm -f $TMPFILE
+   echo "FAILED"
+   exit 1
+fi
+echo "ok"
+rm -f $TMPFILE
+
+echo "Checking custom ARP request packet with VLAN tag and LLC/SNAP framing against $SAMPLE06 ..."
+ARPARGS="--retry=1 --file=- --destaddr=11:11:11:11:11:11 --srcaddr=22:22:22:22:22:22 --prototype=0x3333 --arphrd=0x4444 --arppro=0x5555 --arphln=0x66 --arppln=0x77 --arpop=0x8888 --arpsha=99:99:99:99:99:99 --arpspa=170.170.170.170 --arptha=bb:bb:bb:bb:bb:bb --vlan=0xddd --llc"
+echo "204.204.204.204" | $srcdir/arp-scan $ARPARGS --writepkttofile=$TMPFILE >/dev/null 2>&1
+if test $? -ne 0; then
+   rm -f $TMPFILE
+   echo "FAILED"
+   exit 1
+fi
+cmp -s $TMPFILE $SAMPLE06
 if test $? -ne 0; then
    rm -f $TMPFILE
    echo "FAILED"
