Added new packet decode tests

diff --git a/check-decode b/check-decode
--- a/check-decode
+++ b/check-decode
@@ -37,6 +37,8 @@ SAMPLE05="$srcdir/pkt-net1921681-response.pcap"
 SAMPLE06="$srcdir/pkt-trailer-response.pcap"
 SAMPLE07="$srcdir/pkt-vlan-llc-response.pcap"
 SAMPLE08="$srcdir/pkt-dup-response.pcap"
+SAMPLE09="$srcdir/pkt-diff-frame-addr.pcap"
+SAMPLE10="$srcdir/pkt-local-admin.pcap"
 
 # Simple ARP response packet
 echo "Checking simple ARP response packet decode using $SAMPLE01 ..."
@@ -361,7 +363,7 @@ rm -f "$ARPSCANOUTPUT"
 rm -f "$EXAMPLEOUTPUT"
 
 # ARP response packets with ignored duplicates
-echo "Checking ARP responses packets with ignored duplicates using $SAMPLE08 ..."
+echo "Checking ARP response packets with ignored duplicates using $SAMPLE08 ..."
 cat >"$EXAMPLEOUTPUT" <<_EOF_
 192.168.14.2	00:50:56:e4:9a:83	VMware, Inc.
 192.168.14.1	00:50:56:c0:00:08	VMware, Inc.
@@ -389,3 +391,104 @@ echo "ok"
 rm -f "$ARPSCANOUTPUT"
 rm -f "$EXAMPLEOUTPUT"
 
+# Simple ARP response with rount-trip time (RTT).
+# We cannot predict the RTT number so we use sed to change it to a fixed number.
+echo "Checking simple ARP response with round-trip time (RTT) display using $SAMPLE01 ..."
+cat >"$EXAMPLEOUTPUT" <<_EOF_
+127.0.0.1	08:00:2b:06:07:08	DIGITAL EQUIPMENT CORPORATION	RTT=999.999 ms
+
+_EOF_
+ARPARGS="--retry=1 --ignoredups --ouifile=$srcdir/ieee-oui.txt --iabfile=$srcdir/ieee-iab.txt --macfile=$srcdir/mac-vendor.txt --rtt"
+./arp-scan $ARPARGS --readpktfromfile="$SAMPLE01" 127.0.0.1 | grep -v '^Starting arp-scan ' | grep -v '^Interface: ' | grep -v '^Ending arp-scan ' | grep -v '^[0-9]* packets received ' | sed 's/RTT=[0-9]*\.[0-9]* ms/RTT=999.999 ms/' > "$ARPSCANOUTPUT" 2>&1
+if test $? -ne 0; then
+   rm -f "$ARPSCANOUTPUT"
+   rm -f "$EXAMPLEOUTPUT"
+   echo "FAILED"
+   exit 1
+fi
+cmp -s "$ARPSCANOUTPUT" "$EXAMPLEOUTPUT"
+if test $? -ne 0; then
+   rm -f "$ARPSCANOUTPUT"
+   rm -f "$EXAMPLEOUTPUT"
+   echo "FAILED"
+   exit 1
+fi
+echo "ok"
+rm -f "$ARPSCANOUTPUT"
+rm -f "$EXAMPLEOUTPUT"
+
+# Simple ARP response packet with --resolve
+echo "Checking simple ARP response with --resolve using $SAMPLE01 ..."
+echo "(this test will fail if 127.0.0.1 does not resolve to \"localhost\")"
+cat >"$EXAMPLEOUTPUT" <<_EOF_
+localhost	08:00:2b:06:07:08	DIGITAL EQUIPMENT CORPORATION
+
+_EOF_
+ARPARGS="--retry=1 --ouifile=$srcdir/ieee-oui.txt --iabfile=$srcdir/ieee-iab.txt --macfile=$srcdir/mac-vendor.txt --resolve"
+./arp-scan $ARPARGS --readpktfromfile="$SAMPLE01" 127.0.0.1 | grep -v '^Starting arp-scan ' | grep -v '^Interface: ' | grep -v '^Ending arp-scan ' | grep -v '^[0-9]* packets received ' > "$ARPSCANOUTPUT" 2>&1
+if test $? -ne 0; then
+   rm -f "$ARPSCANOUTPUT"
+   rm -f "$EXAMPLEOUTPUT"
+   echo "FAILED"
+   exit 1
+fi
+cmp -s "$ARPSCANOUTPUT" "$EXAMPLEOUTPUT"
+if test $? -ne 0; then
+   rm -f "$ARPSCANOUTPUT"
+   rm -f "$EXAMPLEOUTPUT"
+   echo "FAILED"
+   exit 1
+fi
+echo "ok"
+rm -f "$ARPSCANOUTPUT"
+rm -f "$EXAMPLEOUTPUT"
+
+# ARP response with Ethernet frame source address != ar$sha in the ARP packet
+echo "Checking ARP response with Ethernet frame source address != ar\$sha using $SAMPLE09 ..."
+cat >"$EXAMPLEOUTPUT" <<_EOF_
+127.0.0.1	08:00:2b:06:07:08 (08:00:2b:08:07:06)	DIGITAL EQUIPMENT CORPORATION
+
+_EOF_
+ARPARGS="--retry=1 --ouifile=$srcdir/ieee-oui.txt --iabfile=$srcdir/ieee-iab.txt --macfile=$srcdir/mac-vendor.txt"
+./arp-scan $ARPARGS --readpktfromfile="$SAMPLE09" 127.0.0.1 | grep -v '^Starting arp-scan ' | grep -v '^Interface: ' | grep -v '^Ending arp-scan ' | grep -v '^[0-9]* packets received ' > "$ARPSCANOUTPUT" 2>&1
+if test $? -ne 0; then
+   rm -f "$ARPSCANOUTPUT"
+   rm -f "$EXAMPLEOUTPUT"
+   echo "FAILED"
+   exit 1
+fi
+cmp -s "$ARPSCANOUTPUT" "$EXAMPLEOUTPUT"
+if test $? -ne 0; then
+   rm -f "$ARPSCANOUTPUT"
+   rm -f "$EXAMPLEOUTPUT"
+   echo "FAILED"
+   exit 1
+fi
+echo "ok"
+rm -f "$ARPSCANOUTPUT"
+rm -f "$EXAMPLEOUTPUT"
+
+# ARP response from locally administered address
+echo "Checking ARP response with locally administered MAC address using $SAMPLE09 ..."
+cat >"$EXAMPLEOUTPUT" <<_EOF_
+127.0.0.1	02:00:00:00:00:00	(Unknown: locally administered)
+
+_EOF_
+ARPARGS="--retry=1 --ouifile=$srcdir/ieee-oui.txt --iabfile=$srcdir/ieee-iab.txt --macfile=$srcdir/mac-vendor.txt"
+./arp-scan $ARPARGS --readpktfromfile="$SAMPLE10" 127.0.0.1 | grep -v '^Starting arp-scan ' | grep -v '^Interface: ' | grep -v '^Ending arp-scan ' | grep -v '^[0-9]* packets received ' > "$ARPSCANOUTPUT" 2>&1
+if test $? -ne 0; then
+   rm -f "$ARPSCANOUTPUT"
+   rm -f "$EXAMPLEOUTPUT"
+   echo "FAILED"
+   exit 1
+fi
+cmp -s "$ARPSCANOUTPUT" "$EXAMPLEOUTPUT"
+if test $? -ne 0; then
+   rm -f "$ARPSCANOUTPUT"
+   rm -f "$EXAMPLEOUTPUT"
+   echo "FAILED"
+   exit 1
+fi
+echo "ok"
+rm -f "$ARPSCANOUTPUT"
+rm -f "$EXAMPLEOUTPUT"
